### PR TITLE
Memory reduction

### PR DESCRIPTION
**Pull request by vit-tucek**
`edges_repo` je list of sets a `edges_directions` je list of lists

### CODE REVIEW

**Comment by PetraVidnerova** [comment]
diky, ja s tim chvilku pockam, nechci to ted davat do masteru

**Comment by vit-tucek** [comment]
master = commit 9a1d84ba77836ecd8dc77bc8d7a15d8c96dca7b3 (to jest stabletown)

**master**
npz: 413 MB
compressed_npz: 109 MB
pickle: 247 MB
RES: 4.5 GB (zhruba)
timeit: 371.3349636460189

**patch**
npz: 151 MB
compressed_npz: 4.5 MB
pickle:  89 MB
RES: 3.5 GB (zhruba)
timeit: 576.7671946129994

Že by žrala čas výroba numpy array v každém kroku? Nebo union množin? Zkusím profiler, jestli se mi vejde do paměti.

**Comment by vit-tucek** [comment]
patch_history.csv
[history.txt](https://github.com/PetraVidnerova/model-m/files/4634919/history.txt)

**Comment by vit-tucek** [comment]
master_history.csv
[master_history.txt](https://github.com/PetraVidnerova/model-m/files/4634928/master_history.txt)

**Comment by cyberklezmer** [comment]
Tohle jsem dostal asi omylem.
M

pá 15. 5. 2020 v 16:24 odesílatel Vít Tuček <notifications@github.com>
napsal:

**Comment by PetraVidnerova** [comment]
to ti asi chodi, protoze jsi v repositari jako spoluautor
klidne ignoruj
P


pá 15. 5. 2020 v 16:35 odesílatel cyberklezmer <notifications@github.com>
napsal:

**Pull request closed without merging**
